@startuml
skinparam backgroundColor #EEEBDC
skinparam handwritten true

title KMC[ng] Application Bootstrapping Diagram
actor Angular
participant AngularRouter
box "KMC[ng] shell"
participant AppNavigator
participant AppShell
participant KalturaAPIConfigAdapter
participant KalturaAuthConfigAdapter
endbox
box "KMC[ng] infrastructure" #LightGreen
participant AppBootstrapRouter as "AppBootstrap (CanActivate)"
participant AppBootstrap
participant AppAuthService
participant AppConfigService
endbox
box "KMC[ng] Server"
participant KMCngServer as "Application Server"
endbox
box "Kaltura Server" #LightBlue
participant KalturaAPI
endbox


== Angular Dependency Injection configuration ==

AppShell --> Angular  : register KalturaAPIConfigAdapter\n[post-config phase]
AppShell --> Angular  : register KalturaAuthConfigAdapter\n[pre-auth phase]
AppShell -> AngularRouter  : assign AppBootstrap\nas 'canActivate' on root route

 == Angular run phase ==

autonumber "<b> [00]"
activate AppBootstrapRouter
AngularRouter -> AppBootstrapRouter : canActivate()
AppBootstrapRouter --> AngularRouter : << observe status >>

AppShell -> AppBootstrap: initApp(defaultConfiguration)
activate AppBootstrap
alt configuration not valid
AppBootstrap -> AppBootstrap : update status to 'error'
AppBootstrap --> AppBootstrapRouter : << status >>
AppBootstrapRouter -> AppNavigator: navigateToError()
AppNavigator -> AngularRouter: navigate to error view
end

hnote over AppBootstrap: << handle 'pre-config' adapters >>
AppBootstrap -> AppConfigService : load(configUri)
activate AppConfigService
AppConfigService -> KMCngServer : get config file
activate KMCngServer
...
KMCngServer --> AppConfigService : << KMC[ng] config >>
destroy KMCngServer

AppConfigService -> AppConfigService: update status initialized
AppConfigService --> AppBootstrap: << initialized | failure >>
destroy AppConfigService

alt failure
AppBootstrap -> AppBootstrap : update status to 'error'
AppBootstrap --> AppBootstrapRouter : << status >>
AppBootstrapRouter -> AppNavigator: navigateToError()
AppNavigator -> AngularRouter: navigate to error view
end

hnote over AppBootstrap: << handle 'post-config' adapters >>

AppBootstrap --> KalturaAPIConfigAdapter : execute()
activate KalturaAPIConfigAdapter
KalturaAPIConfigAdapter -> KalturaAPIConfigAdapter : update kaltura-api configuration
KalturaAPIConfigAdapter --> AppBootstrap
destroy KalturaAPIConfigAdapter


hnote over AppBootstrap: << handle 'pre-auth' adapters >>

AppBootstrap --> KalturaAuthConfigAdapter : execute()
activate KalturaAuthConfigAdapter
KalturaAuthConfigAdapter -> KalturaAuthConfigAdapter : update bootstrapping default,\nlogin and error path configurations
KalturaAuthConfigAdapter --> AppBootstrap
destroy KalturaAuthConfigAdapter

AppBootstrap -> AppAuthService : load()
activate AppAuthService

alt has user token in local storage
    AppAuthService -> AppAuthService : get user token from local storage
    AppAuthService -> KalturaAPI: request user information
    activate KalturaAPI
    ...
    KalturaAPI --> AppAuthService: << user information | nothing if no session >>
    destroy KalturaAPI
    AppAuthService -> AppAuthService: update status authenticated / annonymous
else no user token found
    AppAuthService -> AppAuthService : update status annonymous
end
AppAuthService --> AppBootstrap : << authentication proccess failure >>

alt failure
AppBootstrap -> AppBootstrap : update status to 'error'
AppBootstrap --> AppBootstrapRouter : << status >>
AppBootstrapRouter -> AppNavigator: navigateToError()
AppNavigator -> AngularRouter: navigate to error view
end

AppAuthService --> AppBootstrap : << annonymous user >>
alt user is annonymous
AppAuthService -> AppNavigator: navigateToLogin()
AppNavigator -> AngularRouter: navigate to login page
end

destroy AppAuthService
hnote over AppBootstrap: << handle 'post-auth' adapters >>

AppBootstrap -> AppBootstrap : update status to 'bootstrapped'
AppBootstrap --> AppBootstrapRouter : << status >>

alt user authenticated
AppBootstrapRouter -> AngularRouter : navigate to default view\nallow requested kmcng-app
end

@enduml
